image: $CI_REGISTRY/$CI_PROJECT_PATH/ci-runner:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TAG: latest
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest

before_script:
  - env

cache:
  paths:
    - "node_modules/"
    - "packages/*/node_modules/"

stages:
  - setup
  - test
  - build

"Install Dependencies":
  stage: setup
  script:
    - yarn
    - yarn bootstrap
  # artifacts:
  #   paths:
  #     - node_modules/

"Lint":
  stage: test
  script:
    - yarn lint

"Unit Tests":
  stage: test
  script:
    - yarn test:ci
  artifacts:
    paths:
      - coverage/

"Build Image":
  stage: build
  before_script:
    - echo $GCLOUD_SERVICE_KEY > $HOME/gcloud-service-key.json
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u _json_key --password-stdin https://gcr.io < $HOME/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file $HOME/gcloud-service-key.json
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    refs:
      - master
