image: registry.gitlab.com/protium-network/protium/ci-runner:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - env

cache:
  paths:
    - "node_modules/"
    - "packages/*/node_modules/"

stages:
  - setup
  - test
  - build

"Install Dependencies":
  stage: setup
  script:
    - yarn
    - yarn bootstrap
  # artifacts:
  #   paths:
  #     - node_modules/

"Lint":
  stage: test
  script:
    - yarn lint

"Unit Tests":
  stage: test
  script:
    - yarn test:ci
  artifacts:
    paths:
      - coverage/

"Build Image":
  stage: build
  before_script:
    # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    # - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    # - docker login -u _json_key --password-stdin https://us.gcr.io < ${HOME}/gcloud-service-key.json
  script:
    - docker build -t registry.gitlab.com/protium-network/protium .
    # - docker push registry.gitlab.com/protium-network/protium:latest
  only:
    refs:
      - master
