image: registry.gitlab.com/protium-network/protium/ci-runner:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build

install_project:
  stage: setup
  script:
    - yarn
    - yarn bootstrap
  artifacts:
    paths:
      - node_modules/

lint_project:
  stage: test
  script:
    - yarn lint

test_project:
  stage: test
  script:
    - yarn test:ci
  artifacts:
    paths:
      - coverage/

build_app:
  stage: build
  # before_script:
  #   - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  #   - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  #   - docker login -u _json_key --password-stdin https://us.gcr.io < ${HOME}/gcloud-service-key.json
  script:
    - docker build -t registry.gitlab.com/protium-network/protium .
