image: registry.gitlab.com/protium-network/protium/ci-runner

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - docker login -u _json_key --password-stdin https://us.gcr.io < ${HOME}/gcloud-service-key.json

cache:
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - yarn
    - yarn bootstrap
    - yarn test:ci