image: registry.gitlab.com/protium-network/protium/ci-runner

services:
  - docker:dind

cache:
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - yarn
    - yarn bootstrap
    - yarn test:ci