image: $CI_REGISTRY/$CI_PROJECT_PATH/ci-runner:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CACHE_KEY: $CI_COMMIT_REF_SLUG
  GCLOUD_IMAGE: $GCLOUD_REGISTRY/$CI_PROJECT_PATH
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest

cache:
  key: $CACHE_KEY
  paths:
    - "node_modules/"
    - "packages/*/node_modules/"

stages:
  - setup
  - test
  - build

"Install Dependencies":
  stage: setup
  script:
    - yarn
    - yarn bootstrap

"Audit Dependencies":
  stage: test
  script:
    - yarn audit

"Lint":
  allow_failure: true
  stage: test
  script:
    - yarn lint:ci
  artifacts:
    reports:
      junit: report-lint.xml

"Unit Tests":
  stage: test
  script:
    - yarn test:ci
  artifacts:
    reports:
      junit: report-unit-tests.xml

"Build Image":
  stage: build
  before_script:
    - echo $GCLOUD_SERVICE_KEY > $HOME/gcloud-service-key.json
    - echo $CI_JOB_TOKEN > $HOME/.ci-job-token
    - docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY < $HOME/.ci-job-token
    - docker login -u _json_key --password-stdin $GCLOUD_REGISTRY < $HOME/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file $HOME/gcloud-service-key.json
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $GCLOUD_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker push $GCLOUD_IMAGE
  only:
    refs:
      - master
