version: '3'
services:
  web:
    # image: <tag>
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
